### PR TITLE
Fixed duplication issue

### LINKED ISSUE #7: Check if the city exists before adding
Prevent duplication.

### PR DESCRIPTION
**Pull request by Aatmaj-Zephyr**
Fixed the duplication issue in the frontend side.

### CODE REVIEW

File: Main.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ function submit(){
         window.alert("Error: Please fill out the y coordinate of the city");
     }
     else{
+        if(!city.includes(document.getElementById('citytext').value.toLowerCase())){
```
Comment (Aatmaj-Zephyr) [inline Main.js:51]: If the city is already in the citylist, then don'e accept

File: Main.js [hunk 2]
```diff
@@ -66,7 +67,10 @@ function submit(){
          document.getElementById('addcity').style.display="inline";
          setcities();
     }
-   
+    else{
+        window.alert("Error! City already present");
+    }
```
Comment (Aatmaj-Zephyr) [inline Main.js:72]: Give error

**Review by Aatmaj-Zephyr — COMMENTED** [review]
Fixed it in the frontend side
